language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - 8.0
env:
    - LOWEST="update --prefer-lowest --prefer-stable -n"
    - LOWEST="update"

matrix:
    exclude:
        - php: 7.4
          env: LOWEST="update --prefer-lowest --prefer-stable -n"

before_script:
    - travis_retry composer self-update
    - travis_retry composer ${LOWEST} --no-interaction --prefer-source

script:
    - vendor/bin/phpcs -p
    - vendor/bin/phpstan analyse
    - vendor/bin/tester -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src

after_success:
    - bash <(curl -s https://codecov.io/bash)
